default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5
  host: db
  username: dev
  password: dev
#
development:
  <<: *default
  database: dev

test:
  <<: *default
  database: dev_test

production:
  <<: *default
  database: apps_production
  username: apps
  password: <%= ENV["APPS_DATABASE_PASSWORD"] %>
